### ISSUE TITLE
foundation 5.5

### ISSUE THREAD

**Issue by titaniumbones** [gpspake/grunterie#16]
Hi, have you thought about updating to foundation 5.5?  Do you know if there are any big roadblocks if one tries to do that oneself?  Thanks,

Matt

**Comment by gpspake** [comment]
@titaniumbones Yeah, I should get on that. I've updated some of the projects I'm using this on to 5.5 with no issues; I just haven't updated this repo. If you're comfortable with updating Foundation from the command line, you should be fine; Grunterie is essentially just a [Foundation libsass project](http://foundation.zurb.com/docs/sass.html). If not, I'll probably get around to updating it by this weekend or sooner. Feel free to nag me if I don't :)

**Comment by randomfreeform** [comment]
1st, big thanks for your efforts with Grunter...
Curious what you think of FoundationPress and how it mcompares to Grunterie?
Thanks!!
R

**Comment by gpspake** [comment]
I haven't looked at FoundationPress since I first started working with Foundation but it looks to be well maintained and very similar to Grunterie in how it's organized.

**Comment by gpspake** [comment]
@titaniumbones Grunterie has been updated to Foundation 5.5.5
I made some other improvements as well so check it out and see what you think.
