### ISSUE TITLE
Can't install Grunt or Bower. Help!

### ISSUE THREAD

**Issue by dfill** [gpspake/grunterie#18]
![hello](https://cloud.githubusercontent.com/assets/11167149/6338997/d223b546-bb80-11e4-972b-08af9355e6a7.jpg)

Please refer to the attached image above. I have tried for about 3 hours trying to set this up, but nothing is working. 

I keep getting an error about node-sass.

It works on my home desktop, but not this one (my work one). Please help!

**Comment by dfill** [comment]
Solved it.

1) Go here - http://blog.nodejs.org/2014/10/23/node-v0-10-33-stable/

2) Download and install version 0.10.33 instead of 0.12

3) Install Grunt and Bower

It works!

**Comment by gpspake** [comment]
:+1:
