### ISSUE TITLE
using magellan

### ISSUE THREAD

**Issue by titaniumbones** [gpspake/grunterie#19]
Have you ever used Magellan in a foundation-based theme?  I have a project that would be improved by magellan, but I guess I would need a way to build the magellan menu automatically -- I'm not quite sure how to do that, and if you or anyone else reading this has done it, it would save me a lot of time...  

Thanks,matt

**Comment by jamzth** [comment]
I imagine that you could use a widget area or some sort of shortcode to execute the Magellan sticky menu. I don't see this too difficult of an issue. I'll look at it in the next few days.

**Comment by titaniumbones** [comment]
cool, thanks James.

**Comment by jamzth** [comment]
@titaniumbones Tell me exactly what you want. I got it working with the right html and css. Now it's figuring what you mean by automatically build a menu. It's fairly basic, but has potential in use with shortcodes and even a menu walker class. Anyway, narrow the request down. I'll get it for you.

**Comment by titaniumbones** [comment]
Thank you @jamzth! 

In the visual editor, a user creates a page, segmented by (let's say) ```Heading 2``` headlines.  Wordpress & grunterie then produce HTML something like this:
```
<div class="entry-content">
   <h2>First Section</h2>
    <p>Here is some Text</p>
   <h2>Second Section</h2>
   <p>here is some more text</p>
   <h2>Third Section</h2>
   <p>and a wholebunch more text also.</p>
</div>
```
I would like some js or php that can identify the ```h2``` elements and generate the required markup automatically, without any further intervention on the part of the users.  So the text above becomes:
```
<div data-magellan-expedition="fixed">
  <dl class="sub-nav">
    <dd data-magellan-arrival="first-section"><a href="#first-section">First Section</a></dd>
    <dd data-magellan-arrival="second-section"><a href="#second-section">Second Section</a></dd>
    <dd data-magellan-arrival="third-section"><a href="#third-section">third Section</a></dd>  </dl>
</div>

<div class="entry-content">
<a name="first-section"></a>
<h2 data-magellan-destination="first-section">First Section</h2>
    <p>Here is some Text</p>

<a name="second-section"></a>
<h2 data-magellan-destination="second-section">Second Section</h2>  
   <p>here is some more text</p>

<a name="third-section"></a>
<h2 data-magellan-destination="third-section">Third Section</h2>
   <p>and a wholebunch more text also.</p>
</div>
```
Probably it makes sense to return the ```<divdata-magellan-expedition="fixed">``` markup seperately so that it can be inserted at whatever place seems appropriate (that is, perhaps not at the top of the content; it could go in a sidebar, or off-canvas nav, for instance).  

Does this make sense? Does it seem feasible?

**Comment by jamzth** [comment]
I think it would take extra js, a special page template (maybe), and more time than I realized based on your original post. I think that I can create an easier way with two shortcodes and good documentation. Gonna need a couple more days. I'll go ahead and confess the hack that this may be due to my time constraints. Anyway, I'll post when finished.

**Comment by gpspake** [comment]
Clearing out issues... I haven't really used Magellan with this theme but I have used it successfully with other Foundation projects and it should work fine here too. (In case it matters, I just updated the theme to use Foundation 5.5.2. Not sure if there have been any Magellan specific changes that'll make any difference here.)
