### ISSUE TITLE
How to use full-width rows properly?

### ISSUE THREAD

**Issue by jdfweb** [gpspake/grunterie#20]
Hey all,

I'm working on a client's site and it's going great so far. I have one minor problem, though. On most of the pages I want to use full-width rows. So what I did was this: 

- In header.php, I took out the div class="row" to disable this container on my whole site. This allows me to do full-width designs on any page (see below).

![1](https://cloud.githubusercontent.com/assets/11800545/6998221/18a70838-dba7-11e4-851d-d6d3c7b7b5e7.png)

- Then I would place that row I deleted (the div class="row") on page where I did want a container, and the full-width effect was gone because that page had a container (see below).

![2](https://cloud.githubusercontent.com/assets/11800545/6998223/327acad8-dba7-11e4-8bf6-40d92f8daad2.png)

- So that works great. However, I noticed my blog page was all wonky now. I thought to myself, "okay, lets just put in the div class="row" in the content.php page, which will put the blog right back into a container and it will solve the problem! Nope, it didn't. My blog page still looks like this:

![3](https://cloud.githubusercontent.com/assets/11800545/6998228/5968d234-dba7-11e4-980d-d96660a57f99.png)

Any idea how to fix this? This is the only problem left on my site and it's driving me nuts! Any help would be appreciated.

**Comment by jpagano** [comment]
You've to edit the index.php file.

**Comment by jdfweb** [comment]
With what exactly?

**Comment by jdfweb** [comment]
FIgured it out!

Added this code..

<div class="container" role="document">
	<div class="row">

To the following pages:

single.php, index.php - JUST BELOW the php get header tag.

Hope that helps anyone that may get stuck with this in the future!

**Comment by gpspake** [comment]
Well that was quick :) Glad you got it working. That site looks nice!

**Comment by jdfweb** [comment]
@gpspake Thank you! Just wanted to say thank you so much for implementing this Gruntified version into Reverie :) It's helped me a lot.

I'm not sure if this is within your scope, but do you have any plans with implementing the off-canvas menu? That'd be wicked!

**Comment by gpspake** [comment]
@jdfweb Probably not. I don't want to over-option-ize the theme or make too many opinionated decisions. I also want to keep the theme as close to Reverie as possible. One of the things that initially drew me to Reverie was that it was pretty barebones and closer to an out-of-the-box Foundation project than any of the other themes out there. A lot of the other Foundation themes have options that only work in a few scenarios and seemed to get in the way more than they helped. That being said, adding off canvas to reverie shouldn't bee too much different than adding it to a regular Foundation project.

I personally haven't been very impressed with the Foundation off-canvas component. I've actually fought with it in a number of different projects and ultimately opted for other solutions.

**Comment by jdfweb** [comment]
@gpspake Not a problem! I've tried using it on static HTML sites before too, and trust me I feel your pain haha. Thank you!
