### ISSUE TITLE
How to add picture above the general blog?

### ISSUE THREAD

**Issue by jdfweb** [gpspake/grunterie#21]
So I've added a photo above the single blog posts (single.php), archives (archive.php) - and it works:

![1](https://cloud.githubusercontent.com/assets/11800545/7009890/9acc6eb0-dc6b-11e4-918f-a0d4267fbf9f.jpg)

Tada!

![works](https://cloud.githubusercontent.com/assets/11800545/7009895/a26f6212-dc6b-11e4-92b2-e769b63ae2e8.jpg)

But I'm having trouble adding a header image above the general blog. I tried adding the exact same code at the top of content.php, and my blog went all wonky:

![content](https://cloud.githubusercontent.com/assets/11800545/7009904/ae743d80-dc6b-11e4-9787-a3d39853960f.jpg)

Wonky!

![doesnt-work](https://cloud.githubusercontent.com/assets/11800545/7009909/b50a9892-dc6b-11e4-9bae-09978f783abb.jpg)

How exactly can I add the same effect as the photo above, on the general blog page? Am I inserting the code into the wrong area?

**Comment by randomfreeform** [comment]
jdfweb... thanks so much for sharing code and clear examples! 
Please leave them up for when others like me want to do something similar.

 (And gpspake, thankyou too for any help in all this... this layout is a fairly common desired page layout design these days, sometimes with a floating and re-sizing logo rather then the header text.)

**Comment by jdfweb** [comment]
Noone has an answer??

**Comment by davemac** [comment]
This is WordPress theming question, not really related to Grunterie.

**Comment by jamzth** [comment]
@jdfweb
Adding to content.php will add the image to each post section on the blog page (ie - wonky). Notice that your single.php has 

```php
<div class="container" role="document">
	<div class="row">
```

Adding that header image section places the image outside of the row syntax and give a full-width image that the first example. I keep the container and initial row syntax in my header.php. So giving you an exact place would be difficult. Though I'm fairly certain that you are wanting to place your snippet in the main index above

```php
<div class="container" role="document">
	<div class="row">
```
and maybe with a conditional tag, unless you are making the blog the home page. Hope this helps.

**Comment by jamzth** [comment]
@jdfweb 
You might even be able to just add:
```php
if ( is_front_page() && is_home() ) {
  // your code for front page blog goes here...
} elseif ( is_home() ) {
  // your code if blog isn't front page goes here...
} else {
  // your code for everything else
}
```
to your header.php, depending upon your set up in header. Remember that this will need to go above 
```php
<div class="container" role="document">
	<div class="row">
```
if you want it to work. If I'm understanding you and your alterations to a vanilla Grunterie correctly, this will work.

**Comment by gpspake** [comment]
@jdfweb, hope you got this working. I'm clearing out issues but and I'm going to assume this has been resolved since it's been a while but, If you're still having trouble, feel free to create a new issue :)
