### ISSUE TITLE
Quick question on page-full.php

### ISSUE THREAD

**Issue by squidzink** [gpspake/grunterie#24]
Not really an issue...I'm just curious, why does the full page template include the range slider? I don't recall this in the Reverie version?

Also, @gpspake, after you helped me get through the initial Grunt install about a month ago, I'm finally getting back to trying sass on a real project. It'll be interesting to see if I can swing it. Trial by fire. Setting up the new project with the core stuff already in place was a breeze, though I'm still doing something not quite right. The local grunt files never seem to install into the node_modules folder so I ended up just copying the files from my other project. I may be doing something out of order, since I'm still really flying by the seat of my pants with understanding the tools themselves.

**Comment by gpspake** [comment]
Yep, the [range slider is a foundation component](http://foundation.zurb.com/docs/components/range_slider.html) (All of which are enabled by default) so you should be able to use it anywhere in the theme.

Did you try running `grunt build` before you run `grunt`?

**Comment by squidzink** [comment]
I guess I didn't understand why it the range slider was appearing on the front side of the full page template. I'm honestly not sure what its usage would be there. I just removed it for now. 

Good ran grunt build, but at this point it's hard to say if I did it at the right time. I believe I ran the bower and npm install node-sass@2.0.1 (to avoid the compatibility issue that eat my lunch the first time I tried to set up) then I ran npm install grunt-sass (because something in my notes from the first time indicated I should). I can see I ran grunt build, then rang grunt, which returned an "unable to find local grunt" error. Then I dragged copies from my other install and ran grunt successfully.

I'll try set up for another project and see if I can pay closer attention to the steps I take. I probably should read up on what the hell I'm installing in more detail so I get a grip on what I'm really doing. I am not clear yet on the various components and what they do and how the work together...I like the result though!  While I'm sure my sass is incredibly sloppy at this point and I have to get a real vision on how to leverage its power to be efficient, I'm confident that it is a good path.

**Comment by gpspake** [comment]
Ohhhh. I see what you mean. Sorry; I thought you were asking if would work there. I think what probably happened is I put that there during a previous update to test that it when it was first added to Foundation. I rarely use that full page template so it must have slipped through. I've removed it. Thanks for letting me know about that.

Since the npm dependencies are specified in [package.json](https://github.com/gpspake/grunterie/blob/master/package.json), you should be able to run `npm update` from the project root to get everything you need, you don't need to install them individually. grunt-sass and node-sass are already included there and will be installed when you run npm update.

**Comment by squidzink** [comment]
Ok. I'll see what happens when I set up another. Previously, I'd repeatedly gotten the incompatibility error with the default node-sass version. I don't recall the error now. I'd have to look back through the emails from our original issue conversation. It is what caused the hours of frustration during my initial set up. I'd found the error reported in various discussions on the net and the solution was to specifically install node-sass@2.0.1. Once I'd done that my headache was over and I was up and running. Again, I'm pretty clueless about the tool components so. I don't know why that would have not been a problem for everyone. I'm a little less blind but still cracking my shins as I navigate through this process.

**Comment by gpspake** [comment]
When was that? There were some breaking dependency issues until I [updated it a week or so ago](https://github.com/gpspake/grunterie/commit/83905b2bffc5601958d8a1d03a3edc7cfe5bba8a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). You may get some warnings but if it's still giving you breaking errors, let me know.

**Comment by squidzink** [comment]
It was the first week in June. I'll make sure to start with the current version and test another set up. Thanks!

**Comment by gpspake** [comment]
Ok, then yeah... you may have run in to some trouble. You could try copying the contents of the current package.json in to yours and running npm update for a quick fix but it might be safer to just grab the whole theme as-is.

**Comment by squidzink** [comment]
Will do!
