### ISSUE TITLE
Foundation 6

### ISSUE THREAD

**Issue by jdfweb** [gpspake/grunterie#26]
Hey gpspake,

With the announcement of F6 - will you be upgrading the theme to F6?

Would love if you could!! :)

**Comment by gpspake** [comment]
I plan on it. I try to keep the theme up to date. It might take a minute considering it's a major version change so I don't know how much trouble I'll run in to because of that but it's usually pretty simple.

**Comment by jdfweb** [comment]
Awesome! Glad to hear it :)
